version: '3'

services:
    mysql-hh:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=new_hh
        ports:
            - "33060:33060"
            - "3306:3306"
        volumes:
            - mysql-hh-vol:/var/lib/mysql

    hh-web:
        image: hh_image:test
        ports:
            - "8080:3000"
        depends_on: 
            - mysql-hh
        command: bash -c "cd /codebase/src/ && npx sequelize db:drop && npx sequelize db:create && npx sequelize db:migrate"

volumes:
    mysql-hh-vol:
